spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: false
  datasource:
    url: jdbc:mysql://localhost:3306/bd_usuarios?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
    username: merino
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: ms-usuario-crud
logging:
  level:
   root: info
server:
  port: 8091